### PR TITLE
Add fixes to get running w/ Phoenix 1.3-rc0

### PR DESCRIPTION
**Pull request by mudphone**
- NOTE: Does not move to lib/<base>/web yet. As such, user will have
to add `web` dir to mix.exs `elixirc_paths`
- Bump `phoenix` dep to `1.3-rc0`
- NOTE: Dep `phoenix_swoosh` needs to have its `phoenix` dep bumped
to `1.3-rc0` (I'm currently loading it from local `path:`)
- Use `Ecto.Schema` in user model
- Add `Web` to various Module names, e.g. `<base>.Web.Router.Helpers`

### CODE REVIEW

**Comment by mudphone** [comment]
Created for discussion, as I haven't directed the generated files into the `<base>/lib/<base>/web` directory. Also, the `phoenix_swoosh` dependency needs to bump its `phoenix` dep to `1.3-rc0` before this will work.  I'm curious to hear if this is a good idea or not, as I'm not privy to discussions of the Coherence architecture changes.

**Comment by vircung** [comment]
Would love to see this completed :+1: :heart:

**Comment by mudphone** [comment]
This is working with my deps for Coherence and `phoenix_swoosh` (within this build of Coherence). I must have this Coherence build, and a modified `phoenix_swoosh` parallel to my new phoenix 1.3-rc0 project dir. `phoenix_swoosh` must have it's `phoenix` dep bumped to `1.3-rc0`.

This change moves the files into the new `<my_app>/lib/<my_app>/web` directory specified by Phoenix 1.3. I have placed the auto-generated `users.exs` file in `<my_app>/lib/<my_app>/web/coherence`. I have *not* created a `context.exs` file yet, as I don't know if this is really the best place to put `users.exs`. I'm open to direction here as this is new to me.

By "this is working," I mean that I have installed Coherence in a new Phoenix 1.3-rc0 project, by using `mix coherence.install --full-invitable`. I then updated `router.ex` and `seeds.exs`, and ran `mix ecto.setup`. I was able to log in at `/sessions/new` and create an invite at `/invitations/new`.

**Comment by vircung** [comment]
@mudphone Updated mix to fetch coherence from custom git repository. This should temporary fix problem with application run isolated environment.

**Comment by smpallen99** [comment]
I need to to play with 1.3 for a bit so I understand the new architecture. Hope to get to that soon.

**Comment by mudphone** [comment]
@smpallen99 it looks like changing the location of the user.ex schema file to the new directory structure (for example, to `<my app>/lib/coherence/user.ex`) is a non-trivial change. It requires the change of the module name from `<base>.User` to `<base>.Coherence.User`, assuming it is placed in the `coherence` context dir. 

Also, the 1.3 style, seems to imply that there should be a `<my app>/lib/coherence/coherence.ex` context boundary (api) module too. This would contain a `user_changeset/2` fn that breaks a lot of code due to the fn name and module change.

I am nervous about the changes I'm making because they start to intertwine with the generator code which takes into account the changeset and user module that someone may customize before using Coherence (they may specify a model on the command line, or a changeset in the config file). 

At any rate, those are my thoughts right now and I thought I should just jot them down.

**Comment by vircung** [comment]
I've got functional application vircung/spejs-ex with basic coherence setup at abe4188 and some adjustments at 4d8e39e

**Comment by smpallen99** [comment]
@mudphone I'm working on this PR. You missed a number of items like
* registration update fails because it does not use the new name spaced router helpers module
* many tests don't pass
* incorrect controllers generator path

I make the updates and merge this PR into a coherence branch.

**Comment by smpallen99** [comment]
just created the phx-1.3 branch that should work with phoenix 1.3. All tests are passing.

I would like to restructure coherence to internally adhere to the phoenix 1.3 project structure.

**Comment by mudphone** [comment]
👍 Great, sounds like good news.

**Pull request closed without merging**
