### PR TITLE
Make comeonin password algorithm user configurable

### PR DESCRIPTION
**Pull request by ducky427**
This PR allows the user to configure the password hashing algorithm. For example, you can set the algorithm to `Comeonin.Argon2`. By default, `Comeonin.Bcrypt` is used.

Also upgrades the `comeonin` library.

### CODE REVIEW

**Comment by smpallen99** [comment]
Can you please make this PR pass travis builds. I won't merge until it passes.

**Comment by rohit-lshift** [comment]
Looks like `comeonin "~> 4.0"` requires Erlang 20. :/

**Comment by smpallen99** [comment]
Will your feature work with comeonin 3? If so, we could remove the 4 update and merge this feature. The user can always include comeonin 4 with an override in this project. m

I'm reluctant to remove support for Erlang 19, but perhaps I'm wrong. What do others think?

**Comment by nimish** [comment]
Personally, I would dump erlang 19 and bump the version number

**Comment by GrandathePanda** [comment]
Hey, I opened a feature request a little while ago, but this PR seems like it would allow me to accomplish exactly what I need and generally seems just like a good feature to have for Coherence, imo. I would be willing to take this over and get it in mergeable condition if everyone else is busy or what have you.

**Comment by smpallen99** [comment]
@nimish @GrandathePanda I'm ok with dropping erlang 19 from the build matrix and merging this PR after the following minor updates:

* update the travis build matrix to remove erlang 19 so it passes the travis build
* add small section to the readme explaining the feature with brief example.

@GrandathePanda if we @nimish updates the PR in the next couple days, I'll merge. Then you can add a follow up PR with ur additional enhancements. If we don't hear back from @nimish, then fell free to submit ur own PR and I'll merge it and close this one.

Steve

**Comment by smpallen99** [comment]
@ducky427 I'm in the process of integrating ur PR (manually) and wondering about the `:bcrypt_elixir` dependency. Since we will now have the option to select which hashing algorithm to use, do we really want to include the dependency here? By doing so, we will always have `bcrypt` included event if we don't use it. So, I'm wondering if we should remove the dependency here, and make the user include the one they want in there project... 

Your thoughts?

**Pull request closed without merging**
