### PR TITLE
Replaced CredentialStore Agent with a GenServer

### PR DESCRIPTION
**Pull request by tmbb**
Changes:
- Replaced Agent with GenServer
- We can now change the user data in all sessions and not only the current session.
  We can also change the data from outside a controller.
- Fixed some wrong @specs regarding credentials
- Added a 'credentials' type to enhance readability.

There are lot's of changes, but the commit makes sense as a whole
(except maybe for the tye definitions and fixing the @specs)

Now, in more detail:

*Replaced Agent with a GenServer*
The API remains backward compatible, except for the fact that all
references to Agent are now references to a Server.

A GenServer is a better choice because it abstracts the state further
and allows for more complex queries of the session data.

In this case, a GenServer was necessary to have a fast way of getting
all sessions belonging to a certain user without iterating over all
sessions.

Having a GenServer allows us to keep an (opaque) index, hidden from the
end user (as it should be, given it's an implementation detail).
This extra decoupling between querying the state and the way the state
is in fact stores looks like a good thing.

This GenServer is implemented using ExActor.
ExActor gives an even nicer API on top of the raw GenServer,
and reduces boilerplate by a lot.

It does introduce an extra dependency, but it's compile-time only,
as all macros are expanded at compile-time into a normal GenServer.
The mapping between an ExActor and a GenServer is straightforward,
so I think it doesn't loose much in clarity.
In fact, I think redability is enhanced by not using a raw GenServer.

*Changing the user's data in all sessions*

It requires keeping an additional index in the Credential store,
but it's worth it because it makes it very easy to change the user's
data. Previously, the user had to log out and login so that changes
would be reflected in all sessions.

### CODE REVIEW

**Comment by tmbb** [comment]
All tests pass, but I haven't added any more tests yet.

I have a project in which I've done some manual integration test and it's all working. I'll publish my demo project one of these days after I've had some time to clean up the code.

**Comment by smpallen99** [comment]
I'm in the process of integrating your branch. However, I'm making some changes:

1. Remove exactor. It does not give enough value to add the extra dependency
2. Move the Server record to a simple defstruct. I prefer the simplicity of structs

**Comment by tmbb** [comment]
> Remove exactor. It does not give enough value to add the extra dependency

Fair enough. This is a tradeoff I've thought about. The good thing about genservers is the way you can keep the same API while changing the implementation :)

> I prefer the simplicity of structs

The first version used a simple 2-tuple for the state :p. Later I changed it into a record to make it more obvious. But a struct is probably more idiomatic elixir, so go ahead

**Comment by smpallen99** [comment]
@tmbb Take a look at my refactor-server branch and let me know what you think. I also added some tests for the module. Please note that full projects tests are failing right now. I need to trouble shoot that, but heading to bed now. 

I changed the design of the state. I think it should be more preformant now. The store map values are just the user_data id. And I changed the index map to user_data map, where the key is the user_id, and the value is {user_data, ref_cnt}. 

I also changed the state to a simple map. struct seemed overkill.

**Comment by tmbb** [comment]
I like your new state representation. It saves space and probably makes user updates faster (only on place to update), though without proper benchmarks this is all theoretical. but conceptually I like it.

I haven't looked at the tests yet.

**Comment by smpallen99** [comment]
BTW, forgot to mention before. I have nothing  against `exactor`. I use it on some of my projects. But for a package, I like to keep the dependencies down. Less headaches for our user base if we stick to plain old Elixir where we can.

**Pull request merged**
