### PR TITLE
Contexts

### PR DESCRIPTION
**Pull request by tmbb**
Added support for contexts in the form of a context generator.
The UI changes are described in the README.

From the architectureal point of view this adds a mix task with some mix templates.
Things are moestly copied from the Phx generators with some changes.
The most relevant change is the addition of the `YourApp.YourContext.current_user/1` function that works the same way as the `Coherence.current_user/1` function.

### CODE REVIEW

**Comment by tmbb** [comment]
I'll upload a demo of the new functionality one of these days

**Comment by smpallen99** [comment]
@tmbb Thanks a lot for this PR. I do have a request before I'll merge. Can you please update your branch so it does not show diff for changes already in master. This should have a clean diff with only the changes required to implement the feature. 

Also, I pulled your branch down the other day and it would not compile. It was failing to compile the new context mix task. I cant remember the specific error.

**Comment by tmbb** [comment]
Hm... I'll look into the error.

Sorry for the git mess, I'll try to clean it up.

Just a question: do you think the mix task should allow the user to select the name of the schema (User) and tablr (users), or should it be hardcoded as it is? I think it should be hardcoded, but if you want I can change it.

**Comment by tmbb** [comment]
If you're ok with it, I'll submit a pull request on the phx-1.3 branch instead of creating a new branch. Contexts are the natural evolution of supporting phoenix 1.3, so I don't think a new branch is necessary.

I can't work against the master branch because you've downgraded it to phoenix 1.2

**Comment by tmbb** [comment]
Fuund the error. It's a runtime error, not a compile time error. It's fixed for now, but I don't understand 100% why the fix works. I have to trace the calls into the official Phx generators to make sure I get to the root cause of the bug.

**Pull request closed without merging**
